# ------ root_path/dataset_name ------
root_path: ''


# ------ Load Cache and Features ------
load_cache: False
load_pre_feat: False

# load_cache: True
# load_pre_feat: True


# ------ Hyperparamters ------
search_hp: True
# search_hp: False

search_scale: [30, 30]
search_step: [200, 20]

init_beta: 1
init_alpha: 5


# ------ Basic Config ------
dataset: 'isic2019'
shots: 16
backbone: 'ViT-H/14'
metric: 'f1'

lr: 0.001
augment_epoch: 10
train_epochs: 20